add neard-hotfix-mainnet module
kuutamolabs/near-staking-knd pull request #531
Opened 2023-02-22 09:45 UTC by yanganto

2023-02-22 11:52 UTC, yanganto commented on nix/modules/flake-module.nix
> +        kuutamo.neard.package = lib.mkDefault self.packages.${pkgs.stdenv.hostPlatform.system}.neard { inherit (kuutamo.neard) neardHotFix; };
Hi @Mic92,
Could you help me to pass `neardHotFix` correctly here? :pray:

2023-02-23 09:02 UTC, Mic92 commented on nix/pkgs/neard/generic.nix
>  , darwin
The neardHotFix parameter needs to go here.

2023-02-23 09:02 UTC, Mic92 commented on nix/modules/neard/default.nix
> +    neardHotFix = lib.mkOption {
```suggestion
    neardPatches = lib.mkOption {
```

2023-02-23 09:08 UTC, Mic92 requested changes

2023-02-23 09:08 UTC, Mic92 commented on nix/modules/neard/default.nix
> +      description = "The neard hot fix will apply";
```suggestion
      description = "The patches to apply to the neard package";
```

2023-02-23 09:08 UTC, Mic92 commented on nix/modules/neard/default.nix
> +    neardHotFix = lib.mkOption {
I would also add a `neardRevisionNumber` option here and use this in the neard packages instead of a generic `hotfix` suffix. Because if we are upgrading from one hotfix version to another we won't be able to tell if we upgraded correctly

2023-02-23 09:12 UTC, yanganto commented on nix/modules/neard/default.nix
> +    neardHotFix = lib.mkOption {
currently, it will add hotfix suffix on version
```
  version = if neardHotFix == [ ] then ver else "${version}-hotfix";
```

2023-02-23 09:22 UTC, Mic92 commented on nix/modules/neard/default.nix
> +    neardHotFix = lib.mkOption {
```
version = "${version}${lib.optionalString (revisionNumber != null) "rev${revisionNumber}"}";
```

2023-02-28 13:11 UTC, Mic92 commented
This needs an update now. Otherwise good to go.

2023-02-28 13:11 UTC, Mic92 approved these changes

2023-03-01 01:58 UTC, merged