Add telegraf
kuutamolabs/near-staking-knd pull request #696
Opened 2023-04-26 10:07 UTC by yanganto

2023-04-28 10:54 UTC, Mic92 commented on nix/modules/flake-module.nix
> +      telegrafd = ./telegrafd.nix;
```suggestion
      telegraf = ./telegraf.nix;
```

2023-04-28 10:54 UTC, Mic92 commented on nix/modules/flake-module.nix
> +          self.nixosModules.telegrafd
```suggestion
          self.nixosModules.telegraf
```

2023-04-28 14:57 UTC, Mic92 commented
https://github.com/kuutamolabs/kuutamocore/pull/820 made it running in kuutamo-testnet

2023-05-01 06:34 UTC, yanganto commented
Where is the `prtocol` defined?  Do we already define this in the token?

https://github.com/kuutamolabs/kuutamocore/pull/820/files#r1181368144

2023-05-02 13:40 UTC, Mic92 commented on nix/modules/telegrafd.nix
> +          "http://localhost:3030/metrics"
We also need to monitor kuutamod and the near-exporter (I don't know if have the near exporter yet in the opensource repo, but it's needed for the dashboard).
```suggestion
          "http://localhost:3030/metrics"
          "http://localhost:2233/metrics"
          ] ++ lib.mapAttrsToList (_: inst: "http://${inst.host}:${inst.port}")
            config.services.near-prometheus-exporter.instances;
```

2023-05-02 14:24 UTC, Mic92 commented on nix/modules/telegrafd.nix
> +        ];
```suggestion
```

2023-05-04 08:13 UTC, Mic92 commented on nix/modules/telegrafd.nix
> +          "http://localhost:3030/metrics"
You can move it from our internal repository to this one.

2023-05-04 09:37 UTC, yanganto commented on src/deploy/flake.rs
> +        if let Some(telegraf_config) = &host.telegraf_config {
This allows a user to use Kuutamo's monitoring and his self-host telegraph monitoring at the same time.  

The telegraf_config is not required, if do not want a user to use self-host monitoring and our monitoring at the same time, we can drop this optional configure.

2023-05-04 10:45 UTC, Mic92 commented on src/deploy/flake.rs
> +        if let Some(telegraf_config) = &host.telegraf_config {
But those files are generated and never read by users. You can just have optional values in the the host_toml above with a lot less code.

2023-05-04 10:49 UTC, Mic92 commented on nix/modules/toml-mapping.nix
> +    kuutamo.telegraf.kmonitoring_password = kmonitor_cfg.password;
You could nest these objects in rust for expamle in the config struct:
```suggestion
    kuutamo.telegraf = cfg.telegraf;

    kuutamo.hosted_monitoring = cfg.hosted_monitoring;
```

2023-05-04 11:25 UTC, yanganto commented on src/deploy/flake.rs
> +        if let Some(telegraf_config) = &host.telegraf_config {
Got it.

Will provide `self_monitoring_url`, `self_monitoring_username`, and `self_monitoring_password` fields, and if provided, will use a self-monitoring server.

2023-05-04 11:57 UTC, yanganto commented on src/deploy/flake.rs
> +        if let Some(telegraf_config) = &host.telegraf_config {
`username` will directly use for in telegraf config, `user_id` will prefixed with `protocol`

2023-05-05 02:23 UTC, yanganto commented on src/deploy/flake.rs
> +        if let Some(telegraf_config) = &host.telegraf_config {
There is a prefix in our `username`.  Users possibly do not use the prefix with a self-monitoring server.

2023-05-05 02:54 UTC, yanganto commented on nix/modules/toml-mapping.nix
> +    kuutamo.telegraf.kmonitoring_password = kmonitor_cfg.password;
These parameters are separated intentionally.  Because when `kneard-mgr generate-config /tmp/kneard`, the monitor secrets will store separately,  and try to avoid possible leakage when the user sends out the configuration files for any technical support.

2023-05-05 08:10 UTC, Mic92 commented on nix/modules/near-prometheus-exporterd.nix
> +      }
```suggestion
    };
}
```

2023-05-05 08:14 UTC, Mic92 requested changes

2023-05-05 08:14 UTC, Mic92 commented on nix/modules/flake-module.nix
> +      near-prometheus-exporterd = ./near-prometheus-exporterd.nix;
This module on it's own does not work without the added nixos options in `near-prometheus-exporter.nix`. Just move the configuration of `near-prometheus-exporterd.nix` into a `config = {}` block inside of `near-prometheus-exporter.nix`. No need to have 2 modules.

2023-05-05 08:14 UTC, Mic92 commented on nix/modules/near-prometheus-exporter.nix
> +  };
```suggestion
  };
  config = {
     services.near-prometheus-exporter = {
      # ...
     };
  };
```

2023-05-05 08:19 UTC, Mic92 commented on README.md
> +If you want to self monitor the node, you can set `self_monitoring_url`, `self_monitoring_username`, and `self_monitoring_password` fields of the host for your customized monitor server.
You should probably mention that the Url should point to end Endpoint that implements Prometheus's Remote write API (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)

2023-05-05 08:46 UTC, Mic92 commented on README.md
> +These can be configured by passing options(`--monitor-protocol`, `--monitor-url`, and `--default-token-file`) or environment variables(`KUUTAMO_MONITOR`, `KUUTAMO_MONITOR_PROTOCOL`, and `MONITORING_P
I don't think want to change these settings on the commandline. Please make them all part of the configuration file instead.

2023-05-05 09:02 UTC, yanganto commented on README.md
> +These can be configured by passing options(`--monitor-protocol`, `--monitor-url`, and `--default-token-file`) or environment variables(`KUUTAMO_MONITOR`, `KUUTAMO_MONITOR_PROTOCOL`, and `MONITORING_P
I will remove these documents and `--default-token-file` one.

A user already has the `self_monitoring_url`, `self_monitoring_username`, and `self_monitoring_password` fields to customize the monitor server.

We still need `KUUTAMO_MONITOR`, and `KUUTAMO_MONITOR_PROTOCOL`, if we want to set up a monitor server to test on something.

2023-05-05 09:19 UTC, Mic92 commented on src/deploy/flake.rs
> +        }
Can this one not also be part of the host configuration?

2023-05-05 09:26 UTC, yanganto commented on README.md
> +These can be configured by passing options(`--monitor-protocol`, `--monitor-url`, and `--default-token-file`) or environment variables(`KUUTAMO_MONITOR`, `KUUTAMO_MONITOR_PROTOCOL`, and `MONITORING_P
@Mic92 if we move `--monitor-protocol` as a field of configuration, the `kneard.toml` will involve monitor settings. (currently, there are no monitoring things in the `kneard.toml`)

What should be a good default value if it does not provide?

If we keep it in the environment variable, we can let it default `mainnet` and we modify the dev shell to set it `testnet`.

2023-05-05 09:51 UTC, yanganto commented on src/deploy/flake.rs
> +        }
These parameters are separated intentionally.

Because when `kneard-mgr generate-config /tmp/kneard`, the monitor secrets (username and password in plain text) will store separately, and try to avoid possible leakage when the user sends out the configuration files for any technical support. 

I am thinking about add `--include-secret` for `generate-config`, if not provided the `kmonitor_config.toml` will not store.

2023-05-05 11:25 UTC, yanganto commented
@Mic92 I could not find out the correct way to setup `near prometheus exporter` now. Could we split it as a different PR?

2023-05-05 12:21 UTC, Mic92 commented on src/deploy/flake.rs
> +        }
Makes sense but we also should not add the token to telegraf.toml because this will be leaked into the nix store, which means it could be accidentally uploaded to CI binary caches or remote builder. <- This is also an issue we would be affected by.
In the other pull request I had it therefore written to a separate file and than uploaded as a secret.   

```
services.telegraf.environmentFiles = [ config.kuutamo.telegraf.token_file ];
services.telegraf = {
  extraConfig = {
     outputs = {
          http = {
            url = config.kuutamo.telegraf.url;
            data_format = "prometheusremotewrite";
            username = "${config.kuutamo.telegraf.protocol}-${config.kuutamo.telegraf.user_id}";
            password = "$MONITORING_PASSWORD";
          };
        };
   };
};
```

token_file has than the following format:

```
MONITORING_PASSWORD=<token>
```

2023-05-05 13:50 UTC, Mic92 commented
> @Mic92 I could not find out the correct way to setup `near prometheus exporter` now. Could we split it as a different PR?

ok.

2023-05-05 14:20 UTC, yanganto commented on src/deploy/flake.rs
> +        }
How can I pass the `token_file` when install?  Is there existing module I can follow?

2023-05-08 09:14 UTC, yanganto commented on src/deploy/flake.rs
> +        }
Because the url and username of self monitoring server may also leak some personal information, I move all these into the secret.

2023-05-09 08:33 UTC, Mic92 commented on README.md
> +Self monitoring url should implements [Prometheus's Remote Write API] (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write).
Although monitoring is not mandatory for deploying a node, it is highly recommended. By setting up monitoring, you can easily track metrics and identify potential issues.

To set up monitoring for your node, you can use the Kuutamo monitoring token. The process is simple - just obtain the token and configure your node to send metrics to the Kuutamo monitor. By default, the token name is `kuutamo-monitoring.token`, and the default monitor is `https://mimir.monitoring-00-cluster.kuutamo.computer`.

If you have multiple hosts in `kneard.toml` and want to use different tokens for each host, you can set the `kuutamo_monitoring_token_file` field for each host to point to the desired token file.

Alternatively, if you prefer to self-monitor the node, you can customize your monitor server by setting the `self_monitoring_url`, `self_monitoring_username`, and `self_monitoring_password` fields of the host. The `self_monitoring_url` should implement Prometheus's Remote Write API.

2023-05-09 09:02 UTC, Mic92 commented on nix/modules/telegraf.nix
> +            kmonitor = if "$MONITORING_USERNAME" == "" then { } else {
This does not work because $MONITORING_USERNAME is replaced in the config file.
You are currently comparing static strings

2023-05-09 09:16 UTC, Mic92 commented on nix/modules/telegraf.nix
> +      environmentFiles = [ /var/lib/secrets/telegraf ];
```suggestion
    environmentFiles = [ 
      /var/lib/secrets/telegraf
      (pkgs.writeTextFile "monitoring-passwordhash" config.kuutamo.telegraf.passwordHash)
    ];
```

2023-05-09 09:16 UTC, Mic92 commented on nix/modules/telegraf.nix
> +                url = "$MONITORING_URL";
config.kuutamo.telegraf.url

2023-05-09 09:17 UTC, Mic92 commented on nix/modules/telegraf.nix
> +                username = "$MONITORING_USERNAME";
```suggestion
                username = config.kuutamo.telegraf.url
```

2023-05-09 11:10 UTC, yanganto commented on nix/modules/telegraf.nix
> +                username = "$MONITORING_USERNAME";
Could we just use `config.kuutamo.telegraf.hasMonitoring` to check on the configure is existing or not?  And still, keep the monitoring url and username secret.

Username and the monitor server URL are possibly not a big deal even in self-monitoring, I just feel uncomfortable if any changes that someone's personal information could be aggregated and then leakage from my mistake.

2023-05-10 08:58 UTC, merged